// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function AddRecipeForm(Props) {
  return React.createElement("div", undefined, React.createElement("div", undefined, React.createElement("input", {
                      placeholder: "Title"
                    })), React.createElement("div", undefined, React.createElement("label", undefined, React.createElement("h3", undefined, "Ingredients"), React.createElement("textarea", undefined))), React.createElement("div", undefined, React.createElement("label", undefined, React.createElement("h3", undefined, "Instructions"), React.createElement("textarea", undefined))), React.createElement("button", undefined, "Add!"));
}

var make = AddRecipeForm;

export {
  make ,
  
}
/* react Not a pure module */
