// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.mjs";
import * as React from "react";

function AddRecipeForm(Props) {
  var match = React.useState(function () {
        return "";
      });
  var setTitle = match[1];
  var match$1 = React.useState(function () {
        return "";
      });
  var setIngredients = match$1[1];
  var match$2 = React.useState(function () {
        return "";
      });
  var setInstructions = match$2[1];
  return React.createElement("div", undefined, React.createElement("div", undefined, React.createElement("input", {
                      placeholder: "Title",
                      value: match[0],
                      onChange: (function ($$event) {
                          var title = $$event.target.value;
                          return Curry._1(setTitle, (function (param) {
                                        return title;
                                      }));
                        })
                    })), React.createElement("div", undefined, React.createElement("label", undefined, React.createElement("h3", undefined, "Ingredients"), React.createElement("textarea", {
                          value: match$1[0],
                          onChange: (function ($$event) {
                              var ingredients = $$event.target.value;
                              return Curry._1(setIngredients, (function (param) {
                                            return ingredients;
                                          }));
                            })
                        }))), React.createElement("div", undefined, React.createElement("label", undefined, React.createElement("h3", undefined, "Instructions"), React.createElement("textarea", {
                          value: match$2[0],
                          onChange: (function ($$event) {
                              var instructions = $$event.target.value;
                              return Curry._1(setInstructions, (function (param) {
                                            return instructions;
                                          }));
                            })
                        }))), React.createElement("button", undefined, "Add!"));
}

var make = AddRecipeForm;

export {
  make ,
  
}
/* react Not a pure module */
