// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function AllTags(Props) {
  var tags = Props.tags;
  console.log(tags);
  return React.createElement("div", undefined, "All tags");
}

var make = AllTags;

export {
  make ,
  
}
/* react Not a pure module */
