// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.bs.js";
import * as Store$RescriptReactIntro from "./Store.bs.js";
import * as NavBar$RescriptReactIntro from "./NavBar.bs.js";
import * as AllTags$RescriptReactIntro from "./AllTags.bs.js";

function App(Props) {
  var url = RescriptReactRouter.useUrl(undefined, undefined);
  var match = React.useReducer(Store$RescriptReactIntro.reducer, Store$RescriptReactIntro.initialState);
  var match$1 = url.path;
  var component;
  var exit = 0;
  if (match$1) {
    switch (match$1.hd) {
      case "recipes" :
          var match$2 = match$1.tl;
          if (match$2) {
            var title = match$2.hd;
            if (title === "add") {
              if (match$2.tl) {
                exit = 1;
              } else {
                component = React.createElement("div", undefined, "Add Recipe");
              }
            } else if (match$2.tl) {
              exit = 1;
            } else {
              component = React.createElement("div", undefined, "View Recipe " + title);
            }
          } else {
            exit = 1;
          }
          break;
      case "tags" :
          if (match$1.tl) {
            exit = 1;
          } else {
            component = React.createElement(AllTags$RescriptReactIntro.make, {
                  tags: match[0].tags
                });
          }
          break;
      default:
        exit = 1;
    }
  } else {
    component = React.createElement("div", undefined, "Home page");
  }
  if (exit === 1) {
    component = React.createElement("div", undefined, "Route not found");
  }
  return React.createElement("div", undefined, React.createElement(NavBar$RescriptReactIntro.make, {}), component);
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
