// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CssJs from "bs-css-emotion/src/CssJs.bs.js";

var card = CssJs.style([CssJs.margin({
            NAME: "rem",
            VAL: 2.0
          })]);

var formCard = CssJs.merge([
      card,
      CssJs.style([CssJs.padding({
                  NAME: "rem",
                  VAL: 1.0
                })])
    ]);

export {
  card ,
  formCard ,
  
}
/* card Not a pure module */
