// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CssJs from "bs-css-emotion/src/CssJs.bs.js";
import * as React from "react";
import * as ReactDom from "react-dom";
import * as Caml_option from "bs-platform/lib/es6/caml_option.mjs";
import ReportWebVitals from "./reportWebVitals";
import * as App$RescriptReactIntro from "./App.bs.js";

function reportWebVitals(prim) {
  ReportWebVitals();
  
}

CssJs.$$global("body", [
      CssJs.fontFamily({
            NAME: "custom",
            VAL: "Garamond"
          }),
      CssJs.maxWidth({
            NAME: "rem",
            VAL: 40.0
          }),
      CssJs.border(CssJs.px(1), "solid", CssJs.lightgrey),
      CssJs.margin({
            NAME: "rem",
            VAL: 2.0
          })
    ]);

CssJs.$$global("h1, h2, h3", [
      CssJs.color(CssJs.hex("656565")),
      CssJs.borderBottom(CssJs.px(1), "dashed", CssJs.lightgrey),
      CssJs.maxWidth({
            NAME: "rem",
            VAL: 40.0 / 2.0
          })
    ]);

var rootQuery = document.querySelector("#root");

if (!(rootQuery == null)) {
  ReactDom.render(React.createElement(App$RescriptReactIntro.make, {}), rootQuery);
}

ReportWebVitals();

var rootQuery$1 = (rootQuery == null) ? undefined : Caml_option.some(rootQuery);

export {
  reportWebVitals ,
  rootQuery$1 as rootQuery,
  
}
/*  Not a pure module */
