// Generated by ReScript, PLEASE EDIT WITH CARE

import * as CssJs from "bs-css-emotion/src/CssJs.bs.js";
import * as React from "react";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.bs.js";

function navButton(selected) {
  return CssJs.style([
              CssJs.backgroundColor(selected ? CssJs.hex("656565") : CssJs.hex("efefef")),
              CssJs.padding(CssJs.ex(1.0)),
              CssJs.cursor("pointer")
            ]);
}

var navBar = CssJs.style([
      CssJs.display("flex"),
      CssJs.justifyContent("center"),
      CssJs.borderBottom(CssJs.px(1), "solid", CssJs.hex("656565"))
    ]);

var Styles = {
  navButton: navButton,
  navBar: navBar
};

function NavBar$NavButton(Props) {
  var name = Props.name;
  var selected = Props.selected;
  var linkTo = Props.linkTo;
  return React.createElement("div", {
              className: navButton(selected === name),
              onClick: (function (param) {
                  return RescriptReactRouter.push(linkTo);
                })
            }, name);
}

var NavButton = {
  make: NavBar$NavButton
};

function NavBar(Props) {
  var url = RescriptReactRouter.useUrl(undefined, undefined);
  var match = url.path;
  var selected;
  if (match) {
    switch (match.hd) {
      case "recipes" :
          selected = "Recipes";
          break;
      case "tags" :
          selected = "Tags";
          break;
      default:
        selected = "Home";
    }
  } else {
    selected = "Home";
  }
  return React.createElement("div", {
              className: navBar
            }, React.createElement(NavBar$NavButton, {
                  name: "Home",
                  selected: selected,
                  linkTo: "/"
                }), React.createElement(NavBar$NavButton, {
                  name: "Tags",
                  selected: selected,
                  linkTo: "/tags"
                }), React.createElement(NavBar$NavButton, {
                  name: "Recipes",
                  selected: selected,
                  linkTo: "/recipes/add"
                }));
}

var make = NavBar;

export {
  Styles ,
  NavButton ,
  make ,
  
}
/* navBar Not a pure module */
