// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Array from "bs-platform/lib/es6/belt_Array.mjs";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.bs.js";

function RecipeList(Props) {
  var recipes = Props.recipes;
  return React.createElement("div", undefined, Belt_Array.map(recipes, (function (recipe) {
                    return React.createElement("div", {
                                key: recipe,
                                onClick: (function (param) {
                                    return RescriptReactRouter.push("/recipes/" + recipe);
                                  })
                              }, recipe);
                  })));
}

var make = RecipeList;

export {
  make ,
  
}
/* react Not a pure module */
