// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_MapString from "bs-platform/lib/es6/belt_MapString.mjs";

var initialState = {
  recipes: undefined,
  tags: undefined
};

function reducer(state, action) {
  if (action.TAG !== /* AddRecipe */0) {
    return initialState;
  }
  var title = action.title;
  return {
          recipes: Belt_MapString.set(state.recipes, title, {
                title: title,
                ingredients: action.ingredients,
                instructions: action.instructions,
                tags: []
              }),
          tags: state.tags
        };
}

export {
  initialState ,
  reducer ,
  
}
/* No side effect */
