// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_MapString from "bs-platform/lib/es6/belt_MapString.js";

function ViewRecipe(Props) {
  var state = Props.state;
  var title = Props.title;
  var recipe = Belt_MapString.get(state.recipes, title);
  if (recipe !== undefined) {
    return React.createElement("div", undefined, "View Recipe " + recipe.title);
  } else {
    return React.createElement("div", undefined, title + " is not in our database");
  }
}

var make = ViewRecipe;

export {
  make ,
  
}
/* react Not a pure module */
