// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function ViewRecipe(Props) {
  var title = Props.title;
  return React.createElement("div", undefined, "View Recipe " + title);
}

var make = ViewRecipe;

export {
  make ,
  
}
/* react Not a pure module */
